services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: /api
    image: open-mt_frontend:latest
    container_name: open-mt_frontend_1
    network_mode: host
    restart: unless-stopped